# Site settings
title: Relco Locomotives
baseurl: "" # the subpath of your site, e.g. /blog
url: "relcolocomotives.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
source: ./
destination: ./.tmp/

env: production

exclude: [/scripts/*-expanded.js, .gitignore, gulpfile.js, package.json, .tmp, _site, node_modules]
